# Generated by Django 4.2.4 on 2023-08-06 02:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=25, null=True, unique=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "account",
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wage_after_taxes", models.CharField(max_length=30)),
                ("other_income", models.CharField(max_length=30)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income",
                        to="account.useraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DesiredRequiredSpending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rent", models.IntegerField()),
                ("utilities", models.IntegerField()),
                ("groceries", models.IntegerField()),
                ("loans", models.IntegerField()),
                ("insurance", models.IntegerField()),
                ("phone_bill", models.IntegerField()),
                ("gas", models.IntegerField()),
                ("internet", models.IntegerField()),
                ("other", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="req",
                        to="account.useraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DesiredRequiredSaving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required", models.IntegerField()),
                ("nonrequired", models.IntegerField()),
                ("saving", models.IntegerField()),
                ("loans", models.IntegerField()),
                ("contribution", models.IntegerField()),
                ("other", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saving",
                        to="account.useraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DesiredNonrequiredSpending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clothing", models.IntegerField()),
                ("eating_out", models.IntegerField()),
                ("alcohol", models.IntegerField()),
                ("events", models.IntegerField()),
                ("travel", models.IntegerField()),
                ("recurring_app_payments", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nonreq",
                        to="account.useraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailySpending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_date", models.DateField(default=django.utils.timezone.now)),
                ("rent", models.IntegerField()),
                ("utilities", models.IntegerField()),
                ("groceries", models.IntegerField()),
                ("loans", models.IntegerField()),
                ("insurance", models.IntegerField()),
                ("phone_bill", models.IntegerField()),
                ("gas", models.IntegerField()),
                ("internet", models.IntegerField()),
                ("clothing", models.IntegerField()),
                ("eating_out", models.IntegerField()),
                ("alcohol", models.IntegerField()),
                ("events", models.IntegerField()),
                ("travel", models.IntegerField()),
                ("recurring_app_payments", models.IntegerField()),
                ("other", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily",
                        to="account.useraccount",
                    ),
                ),
            ],
        ),
    ]
