# Generated by Django 4.2.4 on 2023-08-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_model_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desiredrequiredsaving",
            name="required",
            field=models.IntegerField(default=0),
        ),
    ]
