name: Makefile CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Dep
      run: python -m pip install --upgrade pip && pip install poetry

    - name: Install dependencies
      run: make poetry

    - name: Run lint
      run: make lint