name: Makefile CI

on:
  push:
    branches: '**'
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make install

    - name: Run lint
      run: make lint
